import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_LOCALE = "en-US";
const EXCLUDED_LOCALE_MODULES = new Set(["cdn", "cdn.min", "types"]);
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(
    scriptDirectory,
    "../src/core/localeLoaders.generated.ts"
);
const require = createRequire(import.meta.url);
const dateFnsPackagePath = require.resolve("date-fns/package.json");
const dateFnsDirectory = dirname(dateFnsPackagePath);

interface ExportDefinition {
    import?: { default?: string };
}

interface DateFnsPackage {
    exports: Record<string, ExportDefinition>;
}

interface LocaleModule {
    name: string;
    exportName: string;
}

const dateFnsPackage = JSON.parse(
    await readFile(dateFnsPackagePath, "utf8")
) as DateFnsPackage;
const localeModules = await Promise.all(Object.entries(dateFnsPackage.exports)
    .filter(([subpath]) => subpath.startsWith("./locale/"))
    .map(async ([subpath, definition]) => {
        const name = subpath.slice("./locale/".length);
        if (name === DEFAULT_LOCALE || EXCLUDED_LOCALE_MODULES.has(name) || name.includes("/")) {
            return null;
        }

        const modulePath = definition?.import?.default;
        if (!modulePath) {
            throw new Error(`No ESM export found for date-fns locale "${name}".`);
        }

        const source = await readFile(resolve(dateFnsDirectory, modulePath), "utf8");
        const exportName = source.match(/export const ([A-Za-z_$][\w$]*)\s*=/)?.[1];
        if (!exportName) {
            throw new Error(`No locale export found in date-fns module "${name}".`);
        }

        return { name, exportName } satisfies LocaleModule;
    }));

const entries = localeModules
    .filter((entry): entry is LocaleModule => entry !== null)
    .sort((first, second) => first.name < second.name ? -1 : first.name > second.name ? 1 : 0);
const loaders = entries.map(({ name, exportName }) => (
    `    "${name}": () => import("date-fns/locale/${name}")`
    + `.then((module) => module.${exportName})`
));
const loaderNames = entries.map(({ name }) => `    "${name}"`);
const output = `// Generated by scripts/generateLocaleLoaders.ts. Do not edit.\n`
    + `// en-US is loaded synchronously by core/locale.ts.\n\n`
    + `import type { Locale } from "date-fns";\n\n`
    + `export const calendarLocaleLoaderNames: readonly string[] = /* @__PURE__ */ Object.freeze([\n`
    + `${loaderNames.join(",\n")}\n`
    + `]);\n\n`
    + `export const calendarLocaleLoaders: Readonly<Record<string, () => Promise<Locale>>> = /* @__PURE__ */ Object.freeze({\n`
    + `${loaders.join(",\n")}\n`
    + `});\n`;

if (process.argv.includes("--check")) {
    const existing = await readFile(outputPath, "utf8").catch(() => "");
    if (existing.replace(/\r\n/g, "\n") !== output) {
        console.error("Calendar locale loaders are stale. Run npm run locales:generate.");
        process.exitCode = 1;
    }
} else {
    await writeFile(outputPath, output);
}
